import type { ConfirmedOptions } from "@/features/product-options/section-snapshot";
import type { ProductAnalysis } from "@/features/product-analysis/schemas";
import type { FactPolicy, PlannerAsset, PlannerEvidence, PlannerState } from "./schemas";
export type PlannerInput = { evidence: PlannerEvidence[]; assets: PlannerAsset[]; strategy: ProductAnalysis | null;
  restrictedFacts: { factId: string; label: string; status: string }[]; warnings: string[]; confirmedOptions?: ConfirmedOptions };
export type PlannerProvider = { readonly model: string; plan(input: PlannerInput, signal: AbortSignal): Promise<unknown> };
export type PlannerContextInput = { input: PlannerInput; inputFingerprint: string; factPolicy: FactPolicy; assetSnapshot: PlannerAsset[];
  validationStatus: "ready" | "missing" | "stale" | "invalid"; productAnalysisStatus: "ready" | "missing" | "stale" | "invalid";
  coverage: { total: number; completed: number; invalid: number } };
export type PlannerView = { projectId: string; projectName: string; productName: string; detailPageId: string | null;
  extraction?: { assetId: string; hasCandidates: boolean; derivedCount: number }[];
  state: PlannerState | null; inputFingerprint: string | null; stale: boolean; optionsVersion?: number;
  prerequisite: "ready" | "validation_required" | "content_required" | "invalid_input";
  validationStatus: PlannerContextInput["validationStatus"]; productAnalysisStatus: PlannerContextInput["productAnalysisStatus"];
  factPolicy: FactPolicy; assets: PlannerAsset[]; coverage: PlannerContextInput["coverage"] };
